-- Seed sample blog posts for the NGO
INSERT INTO blogs (
  title, 
  slug, 
  content, 
  excerpt, 
  featured_image, 
  author_name, 
  category, 
  tags, 
  status, 
  publish_date, 
  reading_time,
  seo_title,
  seo_description,
  seo_keywords
) VALUES 
(
  'Empowering Rural Communities Through Education',
  'empowering-rural-communities',
  '<h2>Introduction</h2><p>Education is the foundation of sustainable development. At Maa Santoshi Gramin Vikas Samiti, we believe that every child deserves access to quality education, regardless of their geographic location or economic background.</p><h2>Our Approach</h2><p>We have established learning centers in 15 villages across rural India, providing free education to over 2,000 children. Our curriculum combines traditional academics with practical skills training, ensuring students are prepared for both higher education and vocational careers.</p><h2>Impact Stories</h2><p>Meet Priya, a 14-year-old girl from a remote village who dreams of becoming a doctor. Through our scholarship program, she now attends one of the best schools in the district. Her story is just one of many that inspire us to continue our mission.</p><h2>How You Can Help</h2><p>Your support can change lives. Whether through donations, volunteering, or spreading awareness, every contribution makes a difference in the lives of these children.</p>',
  'Discover how our education initiatives are transforming lives in rural communities across India, providing hope and opportunity to thousands of children.',
  '/placeholder.svg?height=600&width=1200',
  'Maa Santoshi Team',
  'Education',
  ARRAY['education', 'rural development', 'children', 'community'],
  'published',
  NOW() - INTERVAL '5 days',
  5,
  'Empowering Rural Communities Through Education | Maa Santoshi',
  'Learn about our education initiatives transforming rural communities in India. Free education for 2000+ children across 15 villages.',
  ARRAY['rural education', 'NGO India', 'child education', 'community development']
),
(
  'Healthcare Initiative: Bringing Medical Care to Remote Villages',
  'healthcare-initiative-remote-villages',
  '<h2>The Challenge</h2><p>Many rural communities in India lack access to basic healthcare facilities. The nearest hospital can be hours away, making timely medical intervention nearly impossible for many families.</p><h2>Our Solution</h2><p>We have launched mobile health clinics that travel to remote villages on a weekly basis. These clinics are staffed by qualified doctors, nurses, and healthcare workers who provide free check-ups, vaccinations, and basic treatments.</p><h2>Key Achievements</h2><ul><li>Over 10,000 medical consultations provided</li><li>5,000 children vaccinated</li><li>200 health awareness workshops conducted</li><li>50 emergency medical evacuations facilitated</li></ul><h2>Maternal Health Focus</h2><p>Our special focus on maternal health has reduced infant mortality rates in our target villages by 40%. Pregnant women receive regular check-ups and nutritional support throughout their pregnancy.</p>',
  'Our mobile health clinics are bringing essential medical care to remote villages, saving lives and improving health outcomes for thousands.',
  '/placeholder.svg?height=600&width=1200',
  'Dr. Sharma',
  'Healthcare',
  ARRAY['healthcare', 'medical camp', 'rural health', 'mobile clinic'],
  'published',
  NOW() - INTERVAL '10 days',
  6,
  'Healthcare Initiative for Remote Villages | Maa Santoshi',
  'Mobile health clinics bringing medical care to remote villages. Over 10,000 consultations and 5,000 vaccinations provided.',
  ARRAY['rural healthcare', 'mobile clinic', 'medical camp India', 'NGO healthcare']
),
(
  'Women Empowerment: Self-Help Groups Transforming Lives',
  'women-empowerment-self-help-groups',
  '<h2>Breaking Barriers</h2><p>In many rural communities, women face significant barriers to economic independence. Traditional roles, lack of education, and limited access to financial resources often keep them trapped in cycles of poverty.</p><h2>Self-Help Group Model</h2><p>We have established 50 Self-Help Groups (SHGs) across our operational areas, empowering over 1,000 women to take control of their financial futures. These groups provide:</p><ul><li>Microfinance and savings opportunities</li><li>Skill development training</li><li>Business mentorship</li><li>Market linkages for products</li></ul><h2>Success Stories</h2><p>Kamla Devi started with a small loan of ₹5,000 to buy a sewing machine. Today, she runs a tailoring business that employs five other women from her village. Her monthly income has increased tenfold.</p><h2>Products and Crafts</h2><p>Our SHG members produce beautiful handicrafts, textiles, and food products that are sold through our network of fair trade partners.</p>',
  'Self-Help Groups are empowering rural women to achieve financial independence and transform their communities.',
  '/placeholder.svg?height=600&width=1200',
  'Maa Santoshi Team',
  'Women Empowerment',
  ARRAY['women empowerment', 'self-help groups', 'microfinance', 'rural women'],
  'published',
  NOW() - INTERVAL '15 days',
  7,
  'Women Empowerment Through Self-Help Groups | Maa Santoshi',
  'Empowering 1000+ rural women through Self-Help Groups. Microfinance, skill training, and business support.',
  ARRAY['women empowerment', 'self help groups India', 'microfinance', 'rural development']
),
(
  'Clean Water Project: Ensuring Safe Drinking Water for All',
  'clean-water-project',
  '<h2>The Water Crisis</h2><p>Access to clean drinking water remains a critical challenge in rural India. Contaminated water sources lead to waterborne diseases, affecting thousands of children and adults every year.</p><h2>Our Intervention</h2><p>Through our Clean Water Project, we have installed hand pumps and water purification systems in 30 villages, providing safe drinking water to over 15,000 people.</p><h2>Community Involvement</h2><p>We believe in community ownership for sustainability. Each village forms a Water Committee responsible for maintaining the water systems. We provide training and support to ensure long-term functionality.</p><h2>Impact</h2><p>Since the project began, we have seen a 60% reduction in waterborne diseases in our target villages. Children are healthier, attending school more regularly, and families are saving money previously spent on medical treatments.</p>',
  'Our clean water initiatives are providing safe drinking water to thousands, dramatically reducing waterborne diseases in rural communities.',
  '/placeholder.svg?height=600&width=1200',
  'Maa Santoshi Team',
  'Environment',
  ARRAY['clean water', 'sanitation', 'rural development', 'health'],
  'published',
  NOW() - INTERVAL '20 days',
  5,
  'Clean Water Project for Rural Villages | Maa Santoshi',
  'Providing safe drinking water to 15,000+ people across 30 villages. 60% reduction in waterborne diseases.',
  ARRAY['clean water India', 'rural sanitation', 'water purification', 'NGO water project']
),
(
  'Sustainable Agriculture: Helping Farmers Thrive',
  'sustainable-agriculture-farmers',
  '<h2>Challenges Facing Rural Farmers</h2><p>Small-scale farmers in India face numerous challenges: unpredictable weather, depleted soil, lack of modern farming techniques, and poor market access. Many struggle to make ends meet despite working tirelessly on their land.</p><h2>Our Agricultural Program</h2><p>We provide comprehensive support to farmers through:</p><ul><li>Training in organic and sustainable farming methods</li><li>Provision of quality seeds and natural fertilizers</li><li>Soil testing and improvement guidance</li><li>Irrigation support through micro-irrigation systems</li><li>Direct market linkages to eliminate middlemen</li></ul><h2>Results</h2><p>Farmers in our program have seen an average 40% increase in crop yields while reducing input costs by 30%. More importantly, they are now practicing sustainable methods that protect the environment for future generations.</p>',
  'Supporting small-scale farmers with sustainable agriculture practices, improving yields and livelihoods across rural communities.',
  '/placeholder.svg?height=600&width=1200',
  'Agricultural Team',
  'Livelihood',
  ARRAY['sustainable agriculture', 'organic farming', 'farmers', 'rural livelihood'],
  'published',
  NOW() - INTERVAL '25 days',
  6,
  'Sustainable Agriculture Program | Maa Santoshi',
  'Supporting farmers with sustainable agriculture training. 40% increase in yields, 30% reduction in input costs.',
  ARRAY['sustainable farming India', 'organic agriculture', 'farmer support', 'rural livelihood']
),
(
  'Youth Skills Development: Building Tomorrow''s Leaders',
  'youth-skills-development',
  '<h2>The Youth Opportunity Gap</h2><p>Rural youth often lack access to quality vocational training and skill development opportunities. This limits their employment prospects and forces many to migrate to cities in search of work.</p><h2>Our Skills Program</h2><p>We have established three Skill Development Centers offering training in:</p><ul><li>Computer literacy and digital skills</li><li>Tailoring and fashion design</li><li>Mobile phone repair</li><li>Electrical work</li><li>Beauty and wellness</li><li>Agriculture technology</li></ul><h2>Placement Support</h2><p>Beyond training, we provide job placement assistance, helping graduates find employment or start their own businesses. Our placement rate exceeds 80%, with many alumni becoming employers themselves.</p><h2>Entrepreneurship</h2><p>For those interested in starting their own ventures, we offer business development support, microloans, and ongoing mentorship.</p>',
  'Equipping rural youth with marketable skills and creating pathways to meaningful employment and entrepreneurship.',
  '/placeholder.svg?height=600&width=1200',
  'Skills Team',
  'Education',
  ARRAY['youth development', 'skill training', 'vocational education', 'employment'],
  'published',
  NOW() - INTERVAL '30 days',
  6,
  'Youth Skills Development Program | Maa Santoshi',
  'Vocational training for rural youth. 80%+ placement rate. Computer skills, tailoring, electrical work, and more.',
  ARRAY['youth skills India', 'vocational training', 'employment program', 'skill development']
)
ON CONFLICT (slug) DO NOTHING;

-- Update the views to show some activity
UPDATE blogs SET views = floor(random() * 500 + 100)::int WHERE status = 'published';
